### ISSUE TITLE
Hydrogen Bond Annotation is Non-Deterministic

### ISSUE THREAD

**Issue by xrobin** [pharmai/plip#50] opened 2020-01-14 10:05 UTC
This might be linked with issue #49 I just opened, but this might be different so I am reporting it separately. Running with Python 3.6.6 and PLIP 1.4.5 from branch `stable`.

I an using [4DST](https://www.rcsb.org/structure/4DST) again as before:

    wget https://files.rcsb.org/download/4DST.pdb
    plipcmd.py -f 4DST.pdb --name 4DST_report -o . -x

Here are two runs that display the problem:

- Run 1: [4DST_report_3.6_1.xml.gz](https://github.com/ssalentin/plip/files/4058187/4DST_report_3.6_1.xml.gz)
- Run 2: [4DST_report_3.6_4.xml.gz](https://github.com/ssalentin/plip/files/4058466/4DST_report_3.6_4.xml.gz)

I normally see 16 hydrogen bonds reported for ligand GCP:202. However if I run the same command again I can sometimes see a 17th bond popping up. In 4DST_report_3.6_4.xml you will see the new bond `id="9"` to VAL:29 on line 1030. It is the same as bond with `id="10"` but with the donor and acceptor atoms swapped.

Only one of the two is reported in XML file 4DST_report_3.6_1.xml.gz.

Is it expected to see different bonds from run to run?

**Comment by fkaiserbio** [comment] 2020-04-30 14:36
We are investigating this issue. It seems to be related to the placement of hydrogens when the structure is protonated with OpenBabel 3. This protonation is non-deterministic and in some cases, small differences in hydrogen placement result in different bonds being reported. This is expected behavior for now and we will reconsider the definition of hydrogen bonds in a future release.

**Comment by fkaiserbio** [comment] 2020-05-12 14:03
This is now considered to be fixed in https://github.com/pharmai/plip/commit/49b0f8ef0ecbbeadf5f15a41023671f01425d50d. Each call to OpenBabel's functions for structure protonation is non-deterministic. Hydrogens may be placed in different 3D locations, based on their degrees of freedom. Due to this behavior, it cannot be guaranteed that the same hydrogen bonds will be annotated across several runs, because angles are calculated tanking hydrogen placement into account. If you want to achieve consistent results over several runs, PLIP now offers:

- writing of the protonated structure to the result directory as `*_protonated.pdb`
- no-protonation flag '--nohydro`

So, if you want to achieve consistent results you should:
- protonate the structure once with PLIP or your tool of preference
- run PLIP with `--nohydro`

**Closed by fkaiserbio** 2020-05-12 14:03 UTC

**Comment by xrobin** [comment] 2020-05-18 07:58
Thanks for checking. I think we can live with slight variations like this if we know this is expected. But it's good to know that there are ways to get stable results if needed.

May I suggest you add a mention of this option in the DOCUMENTATION.md file?

**Comment by fkaiserbio** [comment] 2020-05-18 14:15
You are very welcome! Absolutely, it's already in the doc for `development` branch:
>- Do not protonate structures with non-deterministic OpenBabel routines (`--nohydro`)

Also, I added it to the frontpage README under FAQ:

> > PLIP is reporting different interactions on several runs!
> >
> Due to the non-deterministic nature on how hydrogen atoms can be added to the input structure, it cannot be guaranteed that each run returns exactly the same set of interactions. If you want to make sure to achieve consistent results, you can:
> 
> - protonate the input structure once with PLIP or your tool of preference
> - run PLIP with `--nohydro`
